- .pre-commit-config.yaml
- README.md
- requirements-dev.in
- requirements-dev.txt
> Add pre-commit

- config_dev.env.example
- hauki/settings.py
- hours/api.py
- hours/authentication.py
- hours/tests/test_hauki_signed_auth.py
Start of the "link authentication"
Refs HAUKI-174
> Hauki 174 signed auth

- hauki/settings.py
- hours/authentication.py
- hours/viewsets.py
> Enable rest_framework.authtoken app. Set default authentication classes.

- hours/importer/base.py
- hours/importer/kirjastot.py
- hours/management/commands/hours_import.py
- hours/models.py
- hours/serializers.py
- hours/tests/test_new_models.py
- hours/tests/test_time_element.py
- hours/views.py
Modify kirjastot importer to support the new style periods, time spans, and rules. Also change the TimeElement to dataclass and add more fields to it. The daily opening hours endpoint has also been changed to show only one object per day.
Refs HAUKI-194
> Hauki 194 kirjastot import

- hours/filters.py
- hours/tests/test_parse_filter_date.py
- hours/views.py
> Add support for relative start and end dates in filters

- hours/tests/test_api_permissions.py
- hours/viewsets.py
Can be used to check if the current user has permission to do the
same action on the object.
Refs HAUKI-213
> Add "permission_check" extra action to the model viewsets

- hours/serializers.py
- hours/tests/test_translation_serializer.py
- Only the current language was saved
- If the incoming data didn't include a lang the method would set the value to None
> Fix bugs in the to_internal method

- Dockerfile
- deploy/init_application.sh
- hauki/settings.py
- hours/enums.py
- hours/metadata.py
- hours/tests/test_metadata_translations.py
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
Only for enum choices for now.
Refs HAUKI-261
> Return translations for every language in OPTIONS

- hours/serializers.py
- hours/tests/test_time_spans_api.py
The method is called multiple times when saving nested models.
Also the nested save uses initial_data and not validated_data when saving.
Refs HAUKI-269
> Change TranslationSerializerMixin.to_internal_value to work when nested

- README.md
- hauki/settings.py
- hauki/urls.py
- hours/authentication.py
- hours/views.py
- hours/viewsets.py
- requirements.in
- requirements.txt
Just adds drf_spectacular and adds a couple of descriptions.
Refs HAUKI-29
> Start of the OpenAPI documentation

- azure-pipelines-hauki.yml
This pipeline extends the base pipeline and defines CI and PR triggers in GitHub
> Added Azure DevOps pipeline

- azure-pipelines-hauki.yml
Last line of the file needs to have file extension ".yml" in it.
> Fixed small mistake in azure-pipelines-hauki.yml

- hours/importer/kirjastot.py
- hours/importer/tprek.py
Fix bugs in tprek and kirjasto importers.
See commit messages for more info.
> Importer fixes

- .gitignore
- .pre-commit-config.yaml
- hauki/settings.py
- requirements-dev.in
- requirements-dev.txt
This PR includes small changes I made while setting up the local dev env.
- Install pip-tools to the dev container
- Sync pre-commit tools with dev requirements. Also bump isort, since there were some issues with pre-commit using the current version.
- Small fix to use non-deprecated logger method
> Development env changes

- requirements.txt
> HAUKI-585 | Upgrade python dependencies

- requirements-dev.txt
> HAUKI-585 | Upgrade dev dependencies

- hours/importer/tprek.py
- hours/tests/test_import.py
TPRekImporter: Change deprecated asiointi.hel.fi to tpr.hel.fi
> HAUKI-587 |Replace deprecated URL in tprek importer

- hours/importer/base.py
- hours/importer/kirjastot.py
- hours/models.py
- Add typehints
- Continue library data validation after encountering an error
- Rollback only libraries with bad data (previously rolled everything back if a single library's data check failed)
> HAUKI-474: Improve kirjastot importer

- hours/importer/kirjastot.py
The current version spams a lot of uninformative events to Sentry which each create an issue. This change will raise only a single error per library with extra data in `extra`. Also added some extra logging for status information (check ok, syncing hours, finished import).
The extra data will show up in Sentry's "Additional data" section:
Refs: [HAUKI-474](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-474)
[HAUKI-474]: https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HAUKI-474: Make KirjastotImporter errors more Sentry-friendly

- deploy/entrypoint.sh
- pipelines/hauki-api-release.yml
- pipelines/hauki-api-review.yml
- pipelines/hauki-api-test.yml
refactor pipelines,
[OH-36](https://helsinkisolutionoffice.atlassian.net/browse/OH-36)
[OH-36]: https://helsinkisolutionoffice.atlassian.net/browse/OH-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: refactor pipelines OH-36

- .pre-commit-config.yaml
- README.md
- commitlint.config.js
- sonar-project.properties
> chore: add commit message format requirements

- load-tests/README.md
- load-tests/hauki-scenarios.js
- load-tests/helpers/commands.js
- load-tests/helpers/mocks.js
- load-tests/helpers/utils.js
- load-tests/run.sh
- pipelines/hauki-api-review.yml
Load tests are run against stage environment
[OH-42](https://helsinkisolutionoffice.atlassian.net/browse/OH-42)
[OH-42]: https://helsinkisolutionoffice.atlassian.net/browse/OH-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: k6 load test OH-42

- hours/filters.py
- hours/tests/conftest.py
- hours/tests/test_dateperiod_api.py
- hours/viewsets.py
- locale/en/LC_MESSAGES/django.po
- locale/fi/LC_MESSAGES/django.po
- locale/sv/LC_MESSAGES/django.po
Also fix an error message and fix the resource parameter's type.
> HAUKI-617: Add data source filter in date period list

- hauki/settings.py
- hauki/urls.py
- hours/importer/tprek.py
- hours/models.py
- hours/permissions.py
- hours/tests/test_resource_periods_as_hash.py
- pytest.ini
- requirements-dev.txt
- requirements.in
- requirements.txt
also bump all "easy" applicable dependencies
Refs HAUKI-631
> Upgrade django to 4.2

- requirements-dev.txt
- requirements.in
- requirements.txt
Problems with version 0.27 and above.
Bumps some other deps too.
Refs HAUKI-631
> deps: pin drf-spectacular to 0.26.5

- README.md
Refs [HAUKI-666](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-666) 😈 
[HAUKI-666]: https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README about Ruff

- requirements-dev.txt
Fix missing `six` update from dev requirements.
> deps: fix dev requirements

- requirements-dev.txt
- requirements.txt
Bump requirements reported by dependabot.
> deps: bump certifi and urllib3

- hauki/settings.py
Use latest CORS variable naming convention from: https://pypi.org/project/django-cors-headers/
[HAUKI-663](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-663)
[HAUKI-663]: https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HAUKI-663: Update CORS variable naming
