City-of-Helsinki/hauki

azure-pipelines.yml, deploy/elastic_apm_injection/Dockerfile, deploy/elastic_apm_injection/README, deploy/elastic_apm_injection/local_settings.py
This adds a docker image with Elastic APM support to the build. Still some debug there.
This also refactors docker images into single repository (instead of hauki and hauki_dev), so that pipeline artifacting is much faster.
=> Generate image with Elastic APM support

hauki/settings.py, hours/renderers.py, hours/serializers.py, hours/tests/test_dateperiod_api.py, requirements.in, requirements.txt
Allow saving nested items in the serializers. Also disable HTML forms in the browsable API.
Refs HAUKI-198
=> Nested save in the endpoints

hours/importer/kirjastot.py, requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt
We can uninstall some requirements as they are not used anymore. Also from numpy we used one function that could be replaced easily. This reduces the deployment size roughly in half.
Site packages size:
with the old requirements.txt: 278M
with the old requirements-dev.txt: 404M
with the new requirements.txt: 114M
with the new requirements-dev.txt: 177M
=> Slim down the requirements a bit

hauki/settings.py, hours/models.py, hours/permissions.py, hours/serializers.py, hours/tests/test_api_permissions.py, hours/tests/test_dateperiod_api.py, hours/viewsets.py, users/models.py
- Anyone can read everything
- Only users that are member or admin of a resources organization
can edit or create
- Superusers can edit everything
Refs HAUKI-181
=> Add permission checks to the API endpoints

hauki/settings.py, hours/viewsets.py
I think it's much easier for API consumers to use without needing to make multiple requests. Though I left pagination for the resource endpoint because there are tens of thousands of entries in there. And the consumers don't really need to use the resource list anyway.
=> Remove default pagination, enable pagepagination in ResourceViewSet

hours/api.py, hours/models.py, hours/serializers.py, hours/tests/conftest.py, hours/tests/test_opening_hours_api.py, hours/viewsets.py
The view doesn't support is_public or organization checks yet. Nor does it include child resources that don't have data source defined.
We will do the permission checks and parent data source logic in a separate pull request.
=> Add a new view for querying opening hours for multiple resources

hours/authentication.py, hours/tests/test_hauki_signed_auth.py, hours/views.py
The param names (e.g. source, resource) were too generic. For example in the Date Period list the "resource"-filter clashed with the authentication parameter.
The new parameter names are "hsa_source", "hsa_username", "hsa_created_at", "hsa_valid_until", "hsa_signature", "hsa_organization", and "hsa_resource".
=> Rename Hauki Signed Auth parameters to be more specific

hours/admin.py, hours/management/commands/update_resource_ancestry_fields.py, hours/tests/test_new_models.py, hours/tests/test_resource_api.py, hours/viewsets.py
Adds ability to filter resources by DataSource. Also allows to filter Resources that have no origin id in any data source or in the provided data source.
Additionally
- adds parents and children inlines to the resource admin
- adds "resource_ids" optional argument to update_resource_ancestry_fields-command
=> Hauki 258 filter by missing origin

hours/enums.py, hours/fields.py, hours/serializers.py, hours/tests/conftest.py, hours/tests/test_is_open_now_api.py, hours/tests/test_translation_serializer.py, hours/viewsets.py
Adds a /v1/resource/[resource_id]/is_open_now endpoint. Supports an optional "timezone" parameter for showing the opening hours in that timezone too.
A resource is considered open if there is a matching time span with one of these states:
OPEN, SELF_SERVICE, WITH_KEY, WITH_RESERVATION, WITH_KEY_AND_RESERVATION, ENTER_ONLY
Might want to think about those further.
~TODO:~
~Tests~
~Proper formatting for the "other_timezone_time_now"-field~
Example response without the other timezone:
```json
{
"is_open": true,
"resource_timezone": "Europe/Helsinki",
"resource_time_now": "2021-01-05T15:44:02.799739+02:00",
"matching_opening_hours": [
{
"name": "",
"description": "",
"start_time": "13:00:00",
"end_time": "20:00:00",
"resource_state": "open",
"full_day": false,
"periods": [
9694
]
}
], …
```
=> Simple endpoint for checking if a resource is open right now

hours/authentication.py, hours/models.py, hours/permissions.py, hours/tests/conftest.py, hours/tests/test_api_permissions.py, hours/tests/test_hauki_signed_auth.py, hours/tests/test_resource_ancestry_fields.py, hours/viewsets.py
The flag is only checked when using Hauki Signed Auth.
If the value is False, the user can change only the resource mentioned in the auth parameters or its children.
If True, the user can also change other resources belonging to the same organisation as mentioned in the params.
Refs HAUKI-303
=> Add support for the "has_organization_rights" flag 

hours/tests/test_resource_periods_as_text.py, hours/viewsets.py
Time span data in the denormalized content didn't get updated when date period
was updated via api.
That was because when saving nested serializers, the parent instance gets saved
first and the time spans were updated to the date period later. Which in turn
doesn't trigger denormalized data update because there are no suitable signals
to use when Django updates one-to-many relations.
=> Defer updating denormalized data when updating date period

requirements-dev.txt
Build have been failing for some time: https://dev.azure.com/City-of-Helsinki/hauki/_build/results?buildId=49796&view=logs&j=792982d5-3bb1-5d82-222e-228148b73448&t=54736b9a-3f29-59ec-e3cf-2bd50b89994e
Looks like upgrading Black did the trick. Found help from here https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
Also the `pathspec` and `typing-extensions` needed to be upgraded.
=> Upgrade Black to version 22.3

hours/models.py
We faced an issue where ordering of the rules were different in the CI than in local causing unit tests fail.
We decided that we could order the rules by created to make this ordering in this particular case more robust. Looks like the initial expectation was that the rules should be ordered in the order they are created.
=> Sort rules by created date when generating date_periods_as_text

hours/models.py, hours/tests/test_resource_periods_as_text.py
Sort time span groups with no rules as the first ones so it is easier for the citizens to understand which opening hours stand all  the time.
Now:
```
========================================\n
Aikajakso: 7. marraskuuta 2022 - \n
Aukioloajat:\n\n
Maanantai-Torstai 8.00-16.00 Ajanvarauksella\n\n
Voimassa kun kaikki seuraavat pätevät:\n
- Jokaisen vuoden jokainen parillinen viikko\n\n
---------------------------------------\n\n
Maanantai-Torstai 9.00-15.00 Itsepalvelu\n\n
Voimassa kun kaikki seuraavat pätevät:\n
- Jokaisen vuoden jokainen pariton viikko\n\n
---------------------------------------\n\n
Perjantai 11.00-12.00 Auki\n
Lauantai-Sunnuntai - Suljettu\n\n
========================================\n
```
Later:
```
========================================\n
Aikajakso: 7. marraskuuta …
```
=> Sort time span groups by rules in date periods as text

hours/authentication.py, hours/tests/test_hauki_signed_auth.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, locale/sv/LC_MESSAGES/django.po
- At the moment same user cannot use Aukiolosovellus from both TPR or Varaamo since data source restrictions
- Varaamo is using the same org structure as TPR causing the user not being added to the org causing copying opening hours somewhere in the future to fail
- Remove check for data_source from the user and add the provided data_source to the user instead
- Remove check of data_source from the organization and add the user to the given organization instead
- User can log in from multiple systems e.g Varaamo and TPR.
=> Allow login for same user from multiple systems

hours/importer/tprek.py
At the moment when a unit is marked as non-public in TPR the `https://www.hel.fi/palvelukarttaws/rest/v4/unit/`endpoint won't return that unit anymore. When the importer is run the next morning it will sync the resources with the result from that endpoint and since the unit is not there it will mark that as non-public. This is fine and works as expected.
The issue is that the unit might have some [connections](https://github.com/City-of-Helsinki/hauki/blob/master/hours/enums.py#L57) and when the parent is not found the connections will be deleted and the opening hours lost. This is not desirable.
Use the same kind of handling for all the resources whether those are units or connections. This way we the user won't lose the data whenever she decides to hide the unit for some reason or …
=> Mark existing connection resources as non-public when not found from TPR during import

hours/importer/tprek.py
At the moment when units are fetched from TPR it contains instances from origins that are not supposed to flow to Hauki. PTVOUT is one of these.
Add `connectionmode` `hauki` to `https://www.hel.fi/palvelukarttaws/rest/v4/unit/` request. It is also used when fetching connections via `https://www.hel.fi/palvelukarttaws/rest/v4/connection/`. This way TPR controls which untis & connections should be created as new resources in Hauki or which resources should be hidden.
=> Set connectionmode to hauki when fetching units from TPR

requirements-dev.txt, requirements.txt
Upgrade to latest minor/patch versions, Snyk only gets it half-done (e.g. upgrading Django patch version only in `requirements-dev.txt`, not `requirements.txt`), so might as well do it properly.
=> Upgrade requirements

docker-compose.yml, hours/models.py, hours/tests/test_resource_periods_as_text.py
Fix `DatePeriod` orderings for `Resource.get_date_periods_as_text()`. Also return include start date on `DatePeriod.as_text()` when the end date is displayed.
=> HAUKI-570 | DatePeriod as text fixes

hours/models.py, hours/tests/test_copy_date_periods.py, hours/tests/test_utils.py, hours/tests/utils.py, hours/utils.py, hours/viewsets.py
Add a new query parameter `date_period_ids` in the `/v1/resource/{id}/copy_date_periods/` endpoint, which accepts a comma-separated list of date period ids for specifying which date periods to copy to the target resource.
Also did some refactoring on the `copy_date_periods` tests.
=> HAUKI-582: Add the option to specify which date periods to copy from a resource

deploy/entrypoint.sh, deploy/init_application.sh, hours/viewsets.py, locale/en/LC_MESSAGES/django.po, locale/fi/LC_MESSAGES/django.po, locale/sv/LC_MESSAGES/django.po
The typo was supposed to be fixed in an earlier commit (44059c2), but wasn't.
EDIT: Also removed init_application.sh as it was causing problems (trying to compile messages in an environment where it has no write permissions)
=> Run makemessages, fix typo, remove init_application.sh

hours/filters.py, hours/tests/test_dateperiod_api.py, hours/viewsets.py
Makes possible to filter DatePeriods by linked resource's data sources. Takes the ancestry into an account like it is in opening_hours endpoint
Refs HAUKI-633
=> feat: add resource_data_source filter to date periods

hours/tests/test_dateperiod_api.py, hours/viewsets.py
When filtering dateperiods with resource_data_source filter, enforce the date filter usage in the query to narrow down results and potentially keeping the query in reasonable size.
Refs HAUKI-633
=> feat: enforce date filters with resource data source

hours/importer/kirjastot.py
Holidays were translated to English (instead of Finnish) due to user locale/language. Force to use Finnish translations.
=> fix(kirjastot): use finnish translations for holidays

hours/enums.py, hours/importer/base.py, hours/tests/test_kirjastot_importer.py, users/migrations/0004_userorigin_unique_user_per_data_source.py
Imported time spans seem to be often in different order than our DB order which results in lots of extra writes and history entries.
refs: HAUKI-657
=> fix: sort imported time spans before comparing to DB values

hours/tests/test_opening_hours_api.py, hours/viewsets.py
Limit the excessive number of rows that are being prefetched for speedier
processing of data.
http://localhost:8000/v1/opening_hours/?data_source=tprek&start_date=0w&end_date=4w&page=3&format=json
before: 1200-1300 ms, 9 queries @ 30-40 ms
after: 280-380 ms,  9 queries @ 30-40 ms
----
When filtering using Exists() there is no risk of introducing duplicate
rows.
http://localhost:8000/v1/opening_hours/?data_source=tprek&start_date=0w&end_date=4w&page=3&page_size=10
Query time goes from 30-40 ms to <20 ms
=> Speed up OpeningHours endpoint

hours/tests/test_date_periods_as_text_for_tprek_api.py, hours/viewsets.py
fix: speed up DatePeriodsAsTextForTprek
Filtering DatePeriods that would be filtered in code anyway grants
a significant speed boost for kirkanta resources that have a lot of
historical DatePeriods. Additionally, a small boost is gained by
dropping fields that are not used in rendering the output.
In local tests with data dump from dev:
http://localhost:8000//v1/date_periods_as_text_for_tprek/
?data_source=kirkanta&page=1
count: 149
before: 3000-3900 ms, 9 queries @ 81 ms
after: 380-400 ms, 9 queries @ 37 ms
NOTE: test does 10 queries because it's done with authenticated user
which adds one extra query for the user.
refs: HAUKI-648
=> fix: speed up DatePeriodsAsTextForTprek

.pre-commit-config.yaml, hauki/settings.py
This makes use of the DATABASE_PASSWORD env variable if it has been setupped.
Also bumps commitlint to 9.18.0
Refs RATY-129
=> RATY-129 | Use DATABASE_PASSWORD env variable

hours/importer/base.py
pytest collects tests and does the imports. This triggers register_importer for KirjastotImporter, which then sets the loaded importers to kirjastot only and makes get_importers return kirjastot importer only.
This PR adds a flag for checking whether get_importers has been fully ran at least once.
=> test: fix get_importers for tests

hours/filters.py, hours/tests/test_dateperiod_api.py, hours/tests/test_opening_hours_api.py, hours/tests/test_parse_filter_date.py
There were error, handling returned value of the date string parser. Problem was that the parser could return None value which was compared against other None or date which obviously does not compute.
Solution to this is to fail early on the parser function and handle the error correctly where the parser function is used. This lead to writing error handling to the MaybeRelativeDateField since the viewset using the function was correctly handling errors (just not the None values).
Before this, when giving badly formatted date parameter in the dateperiod end would have been okay and all the periods would be returned - not anymore, now it returns a validation error.
Refs HAUKI-564
=> fix: handle errors while parsing dates in filters

requirements-dev.txt
7.4.1 is not compatible with Python 3.12.
Refs: HAUKI-721
=> deps: upgrade pip-tools

hours/models.py, hours/tests/conftest.py, hours/tests/test_hauki_signed_auth.py, hours/tests/test_import.py
Address the following deprecation warnings:
- [utcnow is deprecated][utcnow-deprecation]
- [factory_boy's post generation hooks stop calling save automatically][factoryboy-deprecation]
- [SoftDeletableModel.objects returns all objects][django-model-utils-deprecation]
- Note that this wasn't fixed as suggested (replacing objects manager references with available_objects manager) since third-party dependencies also use the objects manager
- This could cause unexpected behaviour, so instead, we replace objects with SoftDeletableManager to ensure it functions as before
- [pytest fixtures should not have marks][pytest-deprecation]
Refs: HAUKI-721, HAUKI-727
[pytest-deprecation]: https://docs.pytest.org/en/8.2.x/deprecations.html#applying-a-mark-to-a-fixture-function
[factoryboy-deprecation]: …
=> Fix deprecations
